// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProject = "projects"

// Project mapped from table <projects>
type Project struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string         `gorm:"column:name;not null" json:"name"`
	UserID     int64          `gorm:"column:user_id;not null" json:"user_id"`
	TotalTime  int64          `gorm:"column:total_time;not null" json:"total_time"`
	GoalTime   int64          `gorm:"column:goal_time;not null" json:"goal_time"`
	Deadline   time.Time      `gorm:"column:deadline;not null" json:"deadline"`
	IsEngaging bool           `gorm:"column:is_engaging" json:"is_engaging"`
	StartTime  time.Time      `gorm:"column:start_time" json:"start_time"`
	CreatedAt  *time.Time     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  *time.Time     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	User       *User          `gorm:"foreignKey:UserID" json:"user"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
